version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deploy
    overwrite: yes
permissions:
  - object: /home/ubuntu/deploy
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 300
      runas: ubuntu
      env:
        DEPLOYMENT_GROUP_NAME: '{{DEPLOYMENT_GROUP_NAME}}'
